import React, { Suspense } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import ThreeDViewer from '@/components/3d/ThreeDViewer';
import { Box, Navigation, Compass } from 'lucide-react';
import ModelLoader from '@/components/3d/ModelLoader';

const ThreeDModels = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-grow">
        <div className="container mx-auto px-4 py-8">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-3xl md:text-4xl font-bold mb-4 text-center">Interactive 3D Models</h1>
            <p className="text-gray-600 text-center mb-8">
              Explore fascinating objects and concepts in interactive 3D. Click and drag to rotate, scroll to zoom.
            </p>
            
            <Tabs defaultValue="cube" className="w-full">
              <TabsList className="grid w-full grid-cols-3 mb-8">
                <TabsTrigger value="cube" className="flex items-center justify-center gap-2">
                  <Box className="w-5 h-5" />
                  <span className="hidden sm:inline">Geometric Facts</span>
                </TabsTrigger>
                <TabsTrigger value="compass" className="flex items-center justify-center gap-2">
                  <Compass className="w-5 h-5" />
                  <span className="hidden sm:inline">Earth Model</span>
                </TabsTrigger>
                <TabsTrigger value="navigation" className="flex items-center justify-center gap-2">
                  <Navigation className="w-5 h-5" />
                  <span className="hidden sm:inline">Space Facts</span>
                </TabsTrigger>
              </TabsList>

              <TabsContent value="cube" className="bg-white rounded-lg shadow-md p-4 mb-6 min-h-[400px]">
                <div className="flex flex-col md:flex-row gap-4">
                  <div className="w-full md:w-1/2 bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg overflow-hidden h-[300px] md:h-[400px]">
                    <Suspense fallback={<ModelLoader />}>
                      <ThreeDViewer type="geometric" />
                    </Suspense>
                  </div>
                  <div className="w-full md:w-1/2 p-4">
                    <h2 className="text-2xl font-bold text-purple-600 mb-4">Geometric Facts</h2>
                    <ul className="list-disc pl-5 space-y-3 text-gray-700">
                      <li>The Platonic solids are the only five regular polyhedra: tetrahedron, cube, octahedron, dodecahedron, and icosahedron.</li>
                      <li>A hypercube (or tesseract) is a 4-dimensional analog of a cube.</li>
                      <li>The sum of the angles in any triangle is always 180 degrees.</li>
                      <li>The Möbius strip has only one side and one edge.</li>
                    </ul>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="compass" className="bg-white rounded-lg shadow-md p-4 mb-6 min-h-[400px]">
                <div className="flex flex-col md:flex-row gap-4">
                  <div className="w-full md:w-1/2 bg-gradient-to-br from-blue-50 to-teal-50 rounded-lg overflow-hidden h-[300px] md:h-[400px]">
                    <Suspense fallback={<ModelLoader />}>
                      <ThreeDViewer type="earth" />
                    </Suspense>
                  </div>
                  <div className="w-full md:w-1/2 p-4">
                    <h2 className="text-2xl font-bold text-teal-600 mb-4">Earth Facts</h2>
                    <ul className="list-disc pl-5 space-y-3 text-gray-700">
                      <li>The Earth is not perfectly spherical; it's an oblate spheroid, bulging at the equator.</li>
                      <li>About 71% of Earth's surface is covered by water.</li>
                      <li>The Earth's magnetic field is generated by the movement of molten iron in the outer core.</li>
                      <li>Earth's atmosphere is composed of approximately 78% nitrogen, 21% oxygen, and 1% other gases.</li>
                    </ul>
                  </div>
                </div>
              </TabsContent>

              <TabsContent value="navigation" className="bg-white rounded-lg shadow-md p-4 mb-6 min-h-[400px]">
                <div className="flex flex-col md:flex-row gap-4">
                  <div className="w-full md:w-1/2 bg-gradient-to-br from-purple-50 to-indigo-50 rounded-lg overflow-hidden h-[300px] md:h-[400px]">
                    <Suspense fallback={<ModelLoader />}>
                      <ThreeDViewer type="space" />
                    </Suspense>
                  </div>
                  <div className="w-full md:w-1/2 p-4">
                    <h2 className="text-2xl font-bold text-indigo-600 mb-4">Space Facts</h2>
                    <ul className="list-disc pl-5 space-y-3 text-gray-700">
                      <li>Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.</li>
                      <li>The largest planet in our solar system is Jupiter, with a diameter 11 times that of Earth.</li>
                      <li>A day on Venus is longer than a year on Venus.</li>
                      <li>The Milky Way galaxy contains between 100-400 billion stars.</li>
                    </ul>
                  </div>
                </div>
              </TabsContent>
            </Tabs>
            
            <div className="bg-gray-50 rounded-lg p-6 mt-8">
              <h3 className="text-lg font-medium mb-2">3D Interaction Guide</h3>
              <ul className="list-disc pl-5 text-sm text-gray-600">
                <li><strong>Left-click + drag:</strong> Rotate the model</li>
                <li><strong>Scroll:</strong> Zoom in and out</li>
                <li><strong>Right-click + drag:</strong> Pan the camera</li>
                <li><strong>Double-click:</strong> Reset camera position</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default ThreeDModels;
